# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-27 00:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0002_categories_closed_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='members',
            field=models.ManyToManyField(related_name='member', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='categories',
            name='pending_members',
            field=models.ManyToManyField(related_name='pending_member', to=settings.AUTH_USER_MODEL),
        ),
    ]
