# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-27 08:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0003_auto_20171227_0016'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='super_members',
            field=models.ManyToManyField(related_name='super_member', to=settings.AUTH_USER_MODEL),
        ),
    ]
