# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-28 02:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20171227_0845'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='gateKeeper',
            field=models.CharField(default='Members', max_length=30),
            preserve_default=False,
        ),
    ]
