# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-30 02:20
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('discuss', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name=django.contrib.auth.models.User)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discuss.Post')),
            ],
        ),
        migrations.RenameModel(
            old_name='Discuss',
            new_name='DiscussionType',
        ),
        migrations.AddField(
            model_name='post',
            name='discussionType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discuss.DiscussionType'),
        ),
        migrations.AddField(
            model_name='post',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
