# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-30 02:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discuss', '0002_auto_20171230_0220'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='parentId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='discuss.Reply'),
        ),
    ]
