# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-30 03:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('discuss', '0003_reply_parentid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discussiontype',
            name='category',
        ),
        migrations.AddField(
            model_name='reply',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reply',
            name='content',
            field=models.TextField(),
        ),
    ]
