# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-01 00:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('discuss', '0009_auto_20171231_0250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='original_poster',
        ),
        migrations.AddField(
            model_name='post',
            name='original_poster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
