# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-02 04:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discuss', '0011_auto_20180101_0043'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reply',
            old_name='parentId',
            new_name='parent',
        ),
    ]
