# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-03 18:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discuss', '0012_auto_20180102_0437'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='pub_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='data published'),
        ),
    ]
