# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-26 23:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_categories_closed_category'),
        ('user_profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='pending_member_categories',
            field=models.ManyToManyField(related_name='pending_member', to='home.Categories'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='member_categories',
            field=models.ManyToManyField(related_name='member', to='home.Categories'),
        ),
    ]
