# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-27 00:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profiles', '0002_auto_20171226_2348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='member_categories',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='pending_member_categories',
        ),
    ]
